# Generated by Django 6.0.7 on 2026-08-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_userprofile_id_alter_userprofile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
