# Generated by Django 6.0.7 on 2026-08-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_move_userprofile_to_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
